{% set name = "entry-points-txt" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2bca930f93d510cb1629c434954f7c7166b98c3cc968df7fd3fc270bc3cf06e9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - entry_points_txt
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jwodder/entry-points-txt
  summary: Read & write entry_points.txt files
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beenje
